### ISSUE TITLE
Are you planning to expand this?

### ISSUE THREAD

**Issue by bleuge** [retrohun/blog#2]
maybe cpm/8086? 
Plato rpgs sources? 
A coherent unix distro filled with old games would be sooo nice!
thanks!

**Comment by retrohun** [comment]
Cheers!
Good idea! Some coherent trick and tips are already in queue. Also have external 3rd party goodies like https://www.autometer.de/unix4fun/coherent/index.html
And also a *bsd pcnet driver had been ported to aixps2 by another dude, so I'll give it a try in the future - certain pcnet pci network cards are emulated by VirtualBox that supports aixps2 guest.

**Comment by udo-munk** [comment]
I've build a COHERENT 3.2 system with the whole sources including /usr/games. The complete system can be compiled from a single shell script onto a second HD, which then can be used to boot the self compiled system. I have also populated /usr/local with some more stuff like rogue and  adventure. The disk image is available, boots on PCem and QEMU.

**Comment by bleuge** [comment]
WOW! just Wow! thanks you! 
I definitively try it this weekend.
edit: this is more a suggestion than something to fix, so close this whenever you want. thanks again!

**Comment by retrohun** [comment]
Closing time.
