### ISSUE TITLE
Please give the **i8080 emulator in bash** a free software license

### ISSUE THREAD

**Issue by Low-power** [retrohun/blog#4]
As I commented in https://github.com/retrohun/blog/commit/d882f851cfa49671bb88dc8b1de6ec8f87d23f98?diff=split some time ago, I would like to publish my improvements for this program.
Currently you didn't give any license for this program, so I'm kindly asking for one, to make distributing modified versions possible.

Thanks for considering this, as well as publishing this program in first place.

**Comment by retrohun** [comment]
> As I commented in [d882f85?diff=split](https://github.com/retrohun/blog/commit/d882f851cfa49671bb88dc8b1de6ec8f87d23f98?diff=split) some time ago, I would like to publish my improvements for this program. Currently you didn't give any license for this program, so I'm kindly asking for one, to make distributing modified versions possible.
> 
> Thanks for considering this, as well as publishing this program in first place.

Is it not enough free for the purposes you mentioned?

**Comment by Low-power** [comment]
> Is it not enough free for the purposes you mentioned?

Unfortunately programs without a license cannot be considered as free. For me to publish my versions, I will need a license from you, which explicitly granting me the permission to do that.

For simple permissive license chooses, I recommend the MIT/X11 license, or the FreeBSD license.

See also
https://www.gnu.org/licenses/license-list.html#NoLicense

**Comment by retrohun** [comment]
Won't fix.

**Comment by Low-power** [comment]
I don't need a license anymore:
<https://github.com/rivoreo/i8080ash>
